lib: [
  "_build/install/default/lib/lyra/META"
  "_build/install/default/lib/lyra/dune-package"
  "_build/install/default/lib/lyra/lyra.a"
  "_build/install/default/lib/lyra/lyra.cma"
  "_build/install/default/lib/lyra/lyra.cmi"
  "_build/install/default/lib/lyra/lyra.cmt"
  "_build/install/default/lib/lyra/lyra.cmti"
  "_build/install/default/lib/lyra/lyra.cmx"
  "_build/install/default/lib/lyra/lyra.cmxa"
  "_build/install/default/lib/lyra/lyra.ml"
  "_build/install/default/lib/lyra/lyra.mli"
  "_build/install/default/lib/lyra/opam"
]
libexec: [
  "_build/install/default/lib/lyra/lyra.cmxs"
]
bin: [
  "_build/install/default/bin/lyra"
]
